services:
  gmmx-web:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: gmmx-web
    restart: unless-stopped
    env_file:
      - ../.env.production
    ports:
      - "3000:3000"

  gmmx-nginx:
    image: nginx:1.27-alpine
    container_name: gmmx-web-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.gmmx.app.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - gmmx-web
